

export const users = [
 
  {
    id: 1,
    name: "Bradley Ortiz",
    avatar: "/images/profile-photo.png",
    imageBackground: 'url("/images/image Page 2/atlanta-04-mai-cnn-center-atlanta-04-mai-2013-cnn-center-est-siege-mondial_1002979-7554.jpg")',
    bio: "CNN biography  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto cupiditate eum expedita debitis.",
    createdAt: new Date(),
    details: "It's our job to" + <a href="#">#GoThere</a> + "& tell the most difficult stories. For breaking news, follow" + <a href="#">@CNNBRK</a> + "and download our app" + <a href="#">cnn.com/apps</a>,
    country: "États-Unis",
    verified: true,
    numberAbonnees: 1230,
    nombreDeTweets: 56789,
    nombreAbonnement: 2334
  },
  {
    id: 2,
    name: "CNN",
    avatar: "/images/image Page 2/businessman-reading-daily-news.jpg",
    imageBackground: 'url("/images/image Page 2/atlanta-04-mai-cnn-center-atlanta-04-mai-2013-cnn-center-est-siege-mondial_1002979-7554.jpg")',
    bio: "CNN biography  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto cupiditate eum expedita debitis.", 
    createdAt: new Date(),
    details: "It's our job to" + <a href="#">#GoThere</a> + "& tell the most difficult stories. For breaking news, follow" + <a href="#">@CNNBRK</a> + "and download our app" + <a href="#">cnn.com/apps</a>,
    country: "États-Unis",
    verified: true,
    numberAbonnees: 1230,
    nombreDeTweets: 56789,
    nombreAbonnement: 2334
  },
  {
    id: 3,
    name: "The New York Times",
    avatar: "/images/Profile-Photo-new-york.png",
    imageBackground: 'url("/images/image Page 2/cnn-remporte-top-food-nourriture-saine-typique-indonesienne-souvent-appelee-gado-gado-lotek-se-compose-divers-legumes-oeufs-tempeh-lontong-sauce-aux-arachides-cuisine-rue_954783-671.jpg")',
    bio: "The New York Times biography,  Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto cupiditate eum expedita debitis.",
    createdAt: new Date(),
    details: "It's our job to" + <a href="#">#GoThere</a> + "& tell the most difficult stories. For breaking news, follow" + <a href="#">@CNNBRK</a> + "and download our app" + <a href="#">cnn.com/apps</a>,
    country: "États-Unis",
    numberAbonnees: 1230,
    nombreDeTweets: 56789,
    nombreAbonnement: 2334,
    verified: true,
  },
  {
    id: 4,
    name: "Twitter",
    avatar: "/images/logo-rond-twitter-1536x1536.png",
    imageBackground: 'url("/images/image Page 2/cnn-remporte-top-food-nourriture-saine-typique-indonesienne-souvent-appelee-gado-gado-lotek-se-compose-divers-legumes-oeufs-tempeh-lontong-sauce-aux-arachides-cuisine-rue_954783-671.jpg")',
    bio: "Twitter bio",
    createdAt: new Date(),
    country: "États-Unis",
    verified: true,
    details: "It's our job to" + <a href="#">#GoThere</a> + "& tell the most difficult stories. For breaking news, follow" + <a href="#">@CNNBRK</a> + "and download our app" + <a href="#">cnn.com/apps</a>,
  },

  {
    id: 5,
    name: "DEKO Emmanuel",
    avatar: "/images/Mes photos /1000280517.jpg",
    imageBackground: 'url("/images/Mes photos /Emmanuel-Deko.jpg")',
    bio: "Twitter bio",
    createdAt: new Date(),
    country: "États-Unis",
    verified: true,
    details: "It's our job to" + <a href="#">#GoThere</a> + "& tell the most difficult stories. For breaking news, follow" + <a href="#">@CNNBRK</a> + "and download our app" + <a href="#">cnn.com/apps</a>,
  },
];